return {
  { "<leader>bp", "<Cmd>BufferLineTogglePin<CR>", desc = "Toggle Pin" },
  { "<leader>bxr", "<Cmd>BufferLineCloseRight<CR>", desc = "Delete Buffers to the Right" },
  { "<leader>bxl", "<Cmd>BufferLineCloseLeft<CR>", desc = "Delete Buffers to the Left" },
  { "<leader>W", "<Cmd>BufferLinePickClose<CR>", desc = "Pick to close" },
  { "<leader>w", ":bd<CR>", desc = "Close Buffer" },
  { "<C-1>", "<Cmd>BufferLineGoToBuffer 1<CR>", desc = "Go to buffer 1" },
  { "<C-2>", "<Cmd>BufferLineGoToBuffer 2<CR>", desc = "Go to buffer 2" },
  { "<C-3>", "<Cmd>BufferLineGoToBuffer 3<CR>", desc = "Go to buffer 3" },
  { "<C-4>", "<Cmd>BufferLineGoToBuffer 4<CR>", desc = "Go to buffer 4" },
  { "<C-5>", "<Cmd>BufferLineGoToBuffer 5<CR>", desc = "Go to buffer 5" },
  { "<C-6>", "<Cmd>BufferLineGoToBuffer 6<CR>", desc = "Go to buffer 6" },
  { "<C-7>", "<Cmd>BufferLineGoToBuffer 7<CR>", desc = "Go to buffer 7" },
  { "<leader>bb", "<Cmd>BufferLinePick<CR>", desc = "Pick bufferline" },
  { "<C-h>", "<cmd>BufferLineCyclePrev<cr>", desc = "Prev Buffer" },
  { "<C-l>", "<cmd>BufferLineCycleNext<cr>", desc = "Next Buffer" },
  { "<C-S-H>", "<cmd>BufferLineMovePrev<cr>", desc = "Move buffer prev" },
  { "<C-S-L>", "<cmd>BufferLineMoveNext<cr>", desc = "Move buffer next" },
}
